# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
      UserBundle\Entity\User:
        algorithm: sha512
        encode_as_base64: false
        iterations: 2

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        user:
          entity: { class: UserBundle\Entity\User, property: email }

        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER', 'ROLE_ADMIN'] }


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        user_login:
            pattern: ^/user/login$
            provider: user
            anonymous: ~

        user_register:
            pattern: ^/user/register$
            provider: user
            anonymous: ~

        # secures part of the application
        user:
            pattern: ^/(user|profile)/
            provider: user
            form_login:
                login_path: user_login
                check_path: user_login_check
                default_target_path: user_target
            logout:
                path: user_logout
                target: user_login
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path: /

    access_control:
        - { path: ^/user/login, roles: [IS_AUTHENTICATED_ANONYMOUSLY, IS_AUTHENTICATED_REMEMBERED] }
        - { path: ^/user/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile/, roles: ROLE_USER }