services:
    doctrine.lifecycles.user:
        class: UserBundle\Entity\Lifecycle\UserListener
        arguments: [ @service_container ]
        tags:
            - { name: doctrine.orm.entity_listener }
