<?php

namespace UserBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function save(UserInterface $user)
	{
		$this->getEntityManager()->persist($user);
	}

	public function getRandomUsers($limit = 500) {
		$query = "SELECT * FROM `User` ORDER BY RAND() LIMIT $limit";

		$em = $this->getEntityManager();
		$stmt = $em->getConnection()->prepare($query);
		$stmt->execute();
		return $stmt->fetchAll();
	}
}